global_costmap:
  update_frequency: 0.5
  publish_frequency: 0.5
  transform_tolerance: 0.8
  width: 50
  height: 25
  static_map: true
  rolling_window: true
  inflation_radius: 2.5
  resolution: 0.01
